### ISSUE TITLE
tarantool protobuf support

### ISSUE THREAD

**Issue by despiegk** [Incubaid/tarantool#2]
- get protobuf to work in tarantool, test performance & memory usage
- protobuf 3.0
- make sure prefab is updated to also build required modules for this

**Comment by iwanbk** [comment]
The only Lua lib i found that support protobuf 3 is https://github.com/jinq0123/LuaPbIntf, and i failed to build it on ubuntu 16.04

The other alternative is bind the C implementation https://github.com/protobuf-c/protobuf-c

**Comment by iwanbk** [comment]
> The other alternative is bind the C implementation https://github.com/protobuf-c/protobuf-c

It is not a good path because we will need to add Lua bindings for each generated code.

As for LuaPbInft, there is some progress in build, but still failed.

**Comment by iwanbk** [comment]
> As for LuaPbInft, there is some progress in build, but still failed.

I still failed to build it, but managed to tried it using docker images from the author https://hub.docker.com/r/vkill/luapbintf/.
(it was build 5 months ago, if we tried to build it now, it will failed).
You can try using my docker https://hub.docker.com/r/iwanbk/docker-tarantool-protobuf/ , i added tarantool and luajit.

Unfortunately, luapbintf doesn't work on LuaJIT.

So, we have some options here:
- add luajit support to luapbintf. Still no idea what kind of work we need to do. FYI it has C++ components which might complicate the works

- add partial protobuf 3 support to https://github.com/Neopallium/lua-pb, only features we need.

- let me know the details why we can't use v2, we might have solution for this.

I think we could try to use last option while we are working on the first option

**Comment by despiegk** [comment]
i'll try capnp in Tarantool, I know we did a test with that one once

**Comment by iwanbk** [comment]
> i'll try capnp in Tarantool, I know we did a test with that one once

yep, https://github.com/Incubaid/playenv/tree/master/capnproto/tarantool
