### ISSUE TITLE
does http://fperrad.github.io/lua-Spore/spore/ work with tarantool?

### ISSUE THREAD

**Issue by despiegk** [Incubaid/tarantool#7]
http://fperrad.github.io/lua-Spore/spore/

**Comment by xmonader** [comment]
EDIT:

```
package.loaded['socket'] = nil
```
made it work just fine 

Example: https://github.com/Incubaid/tarantool/tree/master/sporetest

**Comment by xmonader** [comment]
edit: 
```
package.loaded['socket'] = nil
```
made it work just fine

**Comment by xmonader** [comment]
related work: converter from raml to spore 
https://github.com/xmonader/raml2spore
